### ISSUE TITLE
Selalu mendapatkan pesan kesalahan

### ISSUE THREAD

**Issue by heriprastiio** [dikyarga/angka-menjadi-terbilang#6]
error code ENOSELF
error Refusing to install package with name "angka-menjadi-terbilang" under a package
error also called "angka-menjadi-terbilang". Did you name your project the same
error as the dependency you're installing?
error
error For more information, see:
<https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

Saat pertama kali menjalankan npm install angka-menjadi-terbilang --save muncul pesan error diatas. Apakah ada solusi mengenai error diatas?

**Comment by dikyarga** [comment]
Halo, itu perintah untuk menginstall package ini di project lain, untuk berkontribusi ke package ini, kamu tidak perlu menginstall nya.

cukup jalankan `npm install` saja, buat men-download dependencies nya.
